/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Pessoa.Pessoa_Generica;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class Tela_Agendar_Consulta_View extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_Cadastro_Funcionarios_View
     */
    private ArrayList especialidade;
    private ArrayList medico;
    private ArrayList hora;
    public String[] medicoSel;
    public String[] especialidadeSel;
    public int horaSel[];
    
    public Tela_Agendar_Consulta_View() {
        this.especialidade = new ArrayList<String>();
        this.especialidade.add("Selecione: ");
        this.medico = new ArrayList<String>();
        this.medico.add("Selecione: ");
        this.hora = new ArrayList<String>();
        this.hora.add("Selecione: ");
        this.initComponents();
        this.setIcon();
        this.setVisibleHora(false);
        this.setVisibleBoxMedico(false);
        
    }
    public void setVisibleBoxMedico(Boolean value){
        this.Combo_Box_Medica.setEnabled(value);
    }
    public void setVisibleHora(Boolean value){
        this.Combo_Box_Hora.setEnabled(value);
    }
    public void setIcon(){
        initComponents();
         setFrameIcon(new ImageIcon(this.getClass().getResource("../Imagens/princ.png")));
    }
    public String[] setComboBoxMedica(){
        this.medicoSel=null;
        this.medicoSel = new String[medico.size()];
        this.Combo_Box_Medica.removeAllItems();
        for(int i=0;i<medico.size();i++){
            this.medicoSel[i]= new String((String)this.medico.get(i));
            this.Combo_Box_Medica.addItem(this.medicoSel[i]);
        }
        
        return medicoSel;
    }
    public String[] setComboBoxEspecialidade(){
        this.especialidadeSel=null;
        this.especialidadeSel = new String[especialidade.size()];
        this.Combo_Box_Especialidade.removeAllItems();
        for(int i=0;i<especialidade.size();i++){
            this.especialidadeSel[i]= new String((String)this.especialidade.get(i));
            this.Combo_Box_Especialidade.addItem(this.especialidadeSel[i]);
        }
        
        return especialidadeSel;
    }
    public String[] setComboBoxHora(){
        String[] test=new String[hora.size()+1];
        this.horaSel = new int[hora.size()];
        this.Combo_Box_Hora.removeAllItems();
        for(int i=0;i<hora.size();i++){
            test[i]= new String(""+(int)this.hora.get(i));
            this.horaSel[i]= (int)this.hora.get(i);
            this.Combo_Box_Hora.addItem(test[i]);
        }
        
        return test;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Button_Confirmar = new javax.swing.JButton();
        Button_Sair = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        Combo_Box_Especialidade = new javax.swing.JComboBox();
        Combo_Box_Medica = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Text_Data = new javax.swing.JFormattedTextField();
        Combo_Box_Hora = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Text_Nome_Paciente = new javax.swing.JTextField();
        Text_Email = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(960, 610));
        setMinimumSize(new java.awt.Dimension(960, 610));
        setPreferredSize(new java.awt.Dimension(960, 610));
        setVerifyInputWhenFocusTarget(false);

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel11.setText("Agendar Consultas:");

        Button_Confirmar.setText("Confirmar");
        Button_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ConfirmarActionPerformed(evt);
            }
        });

        Button_Sair.setText("Sair");
        Button_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SairActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel24.setText("Especialidade:");

        Combo_Box_Especialidade.setModel(new javax.swing.DefaultComboBoxModel());
        //Combo_Box_Especialidade.setModel(new javax.swing.DefaultComboBoxModel(this.setComboBoxEspecialidade()));
        Combo_Box_Especialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Box_EspecialidadeActionPerformed(evt);
            }
        });

        Combo_Box_Medica.setModel(new javax.swing.DefaultComboBoxModel());
        //Combo_Box_Medica.setModel(new javax.swing.DefaultComboBoxModel(this.setComboBoxMedica()));
        Combo_Box_Medica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Box_MedicaActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel25.setText("Médico:");

        jLabel26.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel26.setText("Data:");

        try {
            Text_Data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Text_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_DataActionPerformed(evt);
            }
        });

        Combo_Box_Hora.setModel(new javax.swing.DefaultComboBoxModel());
        //Combo_Box_Hora.setModel(new javax.swing.DefaultComboBoxModel(this.setComboBoxHora()));

        jLabel27.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel27.setText("Hora:");

        jLabel28.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel28.setText("Nome:");

        Text_Nome_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_Nome_PacienteActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel29.setText("Email:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button_Sair)
                .addGap(27, 27, 27)
                .addComponent(Button_Confirmar)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Combo_Box_Medica, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo_Box_Especialidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Text_Nome_Paciente)
                            .addComponent(Text_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Text_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo_Box_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel11)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(Combo_Box_Especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Combo_Box_Medica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(Text_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(Combo_Box_Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(Text_Nome_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(Text_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Confirmar)
                    .addComponent(Button_Sair))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Button_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_ConfirmarActionPerformed
    public void Button_ConfirmarActionListener(ActionListener evt) {                                                 
        Button_Confirmar.addActionListener(evt);
    }
    private void Button_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SairActionPerformed

    private void Text_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_DataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_DataActionPerformed
    public void Text_DataActionPerformed(ActionListener evt) {                                          
        this.Text_Data.addActionListener(evt);
    }
    private void Text_Nome_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_Nome_PacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_Nome_PacienteActionPerformed

    private void Combo_Box_MedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Box_MedicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_Box_MedicaActionPerformed

    private void Combo_Box_EspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Box_EspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_Box_EspecialidadeActionPerformed
    public void Combo_Box_EspecialidadeActionPerformed(ActionListener evt) {                                                        
        this.Combo_Box_Especialidade.addActionListener(evt);
    }
    public String getNome(){
        return this.Text_Nome_Paciente.getText();
    }
    public String getEmail(){
        return this.Text_Email.getText();
    }
    public void Button_SairActionListener(ActionListener evt) {                                                 
        Button_Sair.addActionListener(evt);
    }
    public String getData(){
        return this.Text_Data.getText();
    }
    public int getHora(){
        return this.horaSel[this.Combo_Box_Hora.getSelectedIndex()];
    }
    public String getEspecialidade(){
        return this.especialidadeSel[this.Combo_Box_Especialidade.getSelectedIndex()];
    }
    public String getMedico(){
        return this.medicoSel[this.Combo_Box_Medica.getSelectedIndex()];
    }
    public void LimpaCadastros(){
        this.Text_Nome_Paciente.setText("");
        this.Text_Email.setText("");
        this.Text_Data.setText("");
        //this.Combo_Box_Especialidade.removeAllItems();
        this.Combo_Box_Hora.setEnabled(false);
        this.Combo_Box_Medica.setEnabled(false);
    }
    public boolean verifica(){
        if(this.Text_Data.getText()!=null && this.Text_Nome_Paciente.getText()!=null
                && this.Text_Email.getText() != null)
            return true;
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Confirmar;
    private javax.swing.JButton Button_Sair;
    private javax.swing.JComboBox Combo_Box_Especialidade;
    private javax.swing.JComboBox Combo_Box_Hora;
    private javax.swing.JComboBox Combo_Box_Medica;
    private javax.swing.JFormattedTextField Text_Data;
    private javax.swing.JTextField Text_Email;
    private javax.swing.JTextField Text_Nome_Paciente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    /**
     * @param especialidade the especialidade to set
     */
    public void setEspecialidade(ArrayList especialidade) {
        this.especialidade = especialidade;
        this.setComboBoxEspecialidade();
    }

    /**
     * @param medico the medico to set
     */
    public void setMedico(ArrayList medico) {
        this.medico = medico;
        this.setComboBoxMedica();
    }

    /**
     * @param hora the hora to set
     */
    public void setHora(ArrayList hora) {
        this.hora = hora;
        this.setComboBoxHora();
    }
    
    public String getespecialidade(int i){
        return (String) this.especialidade.get(i);
    }
    public String getmedico(int i){
        return (String) this.medico.get(i);
    }
    public String gethora(int i){
        return (String) this.hora.get(i);
    }
}
