/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Models.Tela_Informacoes_Model;
import java.awt.Toolkit;
import java.awt.event.ComponentEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author Rodrigo
 */
public class Tela_Informacoes_View extends javax.swing.JInternalFrame {
    public String[] Noticias = {"Consultas", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "","", "", "", "", "", "", "", "", "", "","", "", "", "", "", "", "", "", "", "","", "", "", "", "", "", "", "", "", ""};
    private String entrada = "Bem vindo";
    public void setNoticias(String[] t){        
        for(int i=0;i<t.length;i++)
            this.Noticias[i]=t[i];
        this.atualiza();
    }
    public void atualiza(){
        jList1.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return Noticias.length; }
            public Object getElementAt(int i) { return Noticias[i]; }
        });
        
    }
    /**
     * Creates new form Tela_Informacoes_View
     */
    public Tela_Informacoes_View() {
        this.setLocation(0,0);
        this.setResizable(false);
        this.setIcon();
        initComponents();
    }
    public void setIcon(){
        initComponents();
         setFrameIcon(new ImageIcon(this.getClass().getResource("../Imagens/princ.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Campo_BemVindo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setBorder(null);
        setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        setMaximumSize(new java.awt.Dimension(370, 710));
        setMinimumSize(new java.awt.Dimension(370, 710));
        setPreferredSize(new java.awt.Dimension(370, 710));

        Campo_BemVindo.setFont(new java.awt.Font("Lucida Bright", 0, 24)); // NOI18N
        Campo_BemVindo.setText(entrada);

        jLabel2.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel2.setText("Consultas:");

        jList1.setBackground(new java.awt.Color(240, 240, 240));
        jList1.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            public int getSize() { return Noticias.length; }
            public Object getElementAt(int i) { return Noticias[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Campo_BemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Campo_BemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Campo_BemVindo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the entrada
     */
    public String getEntrada() {
        return entrada;
    }

    /**
     * @param entrada the entrada to set
     */
    public void setEntrada(String entrada) {
        this.entrada = entrada;
        this.Campo_BemVindo.setText(entrada);
    }
}
