/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Pessoa.Pessoa_Generica;
import java.awt.event.ActionListener;
import java.sql.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author Rodrigo
 */
public class Tela_Cadastro_Funcionarios_View extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tela_Cadastro_Funcionarios_View
     */
    public Tela_Cadastro_Funcionarios_View() {
        
        
        this.setIcon();
        initComponents();
    }
    public void setIcon(){
        initComponents();
         setFrameIcon(new ImageIcon(this.getClass().getResource("../Imagens/princ.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Text_Nome_Funcionario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Text_Data_Nascimento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        Radio_Masculino = new javax.swing.JRadioButton();
        Radio_Feminino = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        Box_Estado_Civil = new javax.swing.JComboBox();
        Box_Cargo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Box_Especialidade = new javax.swing.JComboBox();
        Text_Email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Text_Login = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Text_Senha = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Text_CPF = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        Text_RG = new javax.swing.JFormattedTextField();
        jLabel13 = new javax.swing.JLabel();
        Text_Outro = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        Text_Numero = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        Box_Tipo_Logradouro = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        Text_Logradouro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Text_CEP = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        Text_Complemento = new javax.swing.JTextField();
        Text_Bairro = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Text_Cidade = new javax.swing.JTextField();
        Box_Estado = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        Button_Confirmar = new javax.swing.JButton();
        Button_Sair = new javax.swing.JButton();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(960, 610));
        setMinimumSize(new java.awt.Dimension(960, 610));
        setPreferredSize(new java.awt.Dimension(960, 610));
        setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel1.setText("Informações:");

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel2.setText("Estado Civil:");

        Text_Nome_Funcionario.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Text_Nome_Funcionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_Nome_FuncionarioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel3.setText("Data de Nascimento:");

        try {
            Text_Data_Nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Text_Data_Nascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_Data_NascimentoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel4.setText("Sexo:");

        buttonGroup1.add(Radio_Masculino);
        Radio_Masculino.setText("Masculino");
        Radio_Masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_MasculinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(Radio_Feminino);
        Radio_Feminino.setText("Feminino");
        Radio_Feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_FemininoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel5.setText("Nome Do Funcionário:");

        Box_Estado_Civil.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Box_Estado_Civil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado", "Separado", "Divorciado", "Viuvo" }));
        Box_Estado_Civil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_Estado_CivilActionPerformed(evt);
            }
        });

        Box_Cargo.setEditable(true);
        Box_Cargo.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Box_Cargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Médico", "Enfermeiro", "Secretário", "Outro"}));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel6.setText("Cargo:");

        jLabel7.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel7.setText("Especialidade:");

        Box_Especialidade.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Box_Especialidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Outro","Acupuntura","Alergia e Imunologia","Anestesiologia","Angiologia","Oncologia","Cardiologia","Cirurgia Cardiovascular","Cirurgia daMão","Cirurgia de cabeça e pescoço","Cirurgia do Aparelho Digestivo","Cirurgia Geral","Cirurgia Pediátrica","Cirurgia Plástica","CirurgiaTorácica","Cirurgia Vascular","Clínica Médica","Coloproctologia","Dermatologia","Endocrinologia e Metabologia","Endoscopia","Gastroenterologia","Genética médica","Geriatria","Ginecologia e obstetrícia","Hematologia e Hemoterapia","Homeopatia","Infectologia","Mastologia","Medicina de Família e Comunidade","Medicina do Trabalho","Medicina do Tráfego","Medicina Esportiva","Medicina Física e Reabilitação","Medicina Intensiva","Medicina Legal e Perícia Médica","Medicina Nuclear","Medicina Preventiva e Social","Nefrologia","Neurocirurgia","Neurologia","Nutrologia","Obstetrícia","Oftalmologia","Ortopedia eTraumatologia","Otorrinolaringologia","Patologia","Pediatria","Pneumologia","Psiquiatria","Radiologia","Radioterapia","Reumatologia","Urologia"}));
        Box_Especialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_EspecialidadeActionPerformed(evt);
            }
        });

        Text_Email.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Text_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_EmailActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel8.setText("Email:");

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel9.setText("Login:");

        Text_Login.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Text_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_LoginActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel10.setText("Senha:");

        Text_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_SenhaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel11.setText("Documentos:");

        try {
            Text_CPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Text_CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_CPFActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel12.setText("CPF:");

        try {
            Text_RG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Text_RG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_RGActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel13.setText("RG:");

        Text_Outro.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Text_Outro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_OutroActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel14.setText("Outro:");

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel15.setText("Endereço:");

        Text_Numero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        Text_Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_NumeroActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel16.setText("CEP:");

        Box_Tipo_Logradouro.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Box_Tipo_Logradouro.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Rua", "Avenida", "Praça" }));
        Box_Tipo_Logradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Box_Tipo_LogradouroActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel17.setText("Tipo de Logradouro:");

        Text_Logradouro.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Text_Logradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_LogradouroActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel18.setText("Endereço:");

        jLabel19.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel19.setText("Número:");

        try {
            Text_CEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Text_CEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_CEPActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel20.setText("Complemento:");

        Text_Complemento.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Text_Complemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_ComplementoActionPerformed(evt);
            }
        });

        Text_Bairro.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Text_Bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_BairroActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel21.setText("Barirro:");

        jLabel22.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel22.setText("Cidade:");

        Text_Cidade.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Text_Cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_CidadeActionPerformed(evt);
            }
        });

        Box_Estado.setFont(new java.awt.Font("Lucida Sans", 0, 14)); // NOI18N
        Box_Estado.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Acre (AC)","Alagoas (AL)","Amapá (AP)","Amazonas (AM)","Bahia (BA)","Ceará (CE)","Distrito Federal (DF)","Espírito Santo (ES)","Goiás (GO)","Maranhão (MA)","Mato Grosso (MT)","Mato Grosso do Sul (MS)","Minas Gerais (MG)","Pará (PA) ","Paraíba (PB)","Paraná (PR)","ernambuco(PE)","Piauí (PI)","Rio de Janeiro (RJ)","Rio Grande do Norte (RN)","Rio Grande do Sul (RS)","Rondônia (RO)","Roraima (RR)","Santa Catarina (SC)","São Paulo (SP)","Sergipe (SE)","Tocantins (TO)"}));

        jLabel23.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel23.setText("Estado:");

        Button_Confirmar.setText("Confirmar");
        Button_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ConfirmarActionPerformed(evt);
            }
        });

        Button_Sair.setText("Sair");
        Button_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Text_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Box_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Text_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box_Tipo_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Text_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Text_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Text_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Text_Bairro)))
                        .addGap(45, 45, 45))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_Sair)
                        .addGap(27, 27, 27)
                        .addComponent(Button_Confirmar)))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Text_Nome_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(27, 27, 27)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Text_Data_Nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Text_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel10))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(Box_Especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(jLabel8)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Text_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Text_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(Radio_Masculino)
                                .addGap(14, 14, 14)
                                .addComponent(Radio_Feminino)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box_Estado_Civil, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Box_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Text_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Text_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Text_Outro, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text_Data_Nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Text_Nome_Funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Radio_Masculino)
                    .addComponent(Radio_Feminino)
                    .addComponent(jLabel2)
                    .addComponent(Box_Estado_Civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(Box_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Text_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_Especialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Text_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(Text_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Text_CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)
                        .addComponent(Text_Outro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(Text_RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Box_Tipo_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(Text_Logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Text_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Text_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(Text_Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(Text_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(Text_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Box_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_Confirmar)
                    .addComponent(Button_Sair))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void LimpaCadastros(){
        this.Box_Cargo.setSelectedIndex(0);
        this.Box_Especialidade.setSelectedIndex(0);
        this.Box_Estado.setSelectedIndex(0);
        this.Box_Estado_Civil.setSelectedIndex(0);
        this.Box_Tipo_Logradouro.setSelectedIndex(0);
        this.Text_Bairro.setText("");
        this.Text_CEP.setText("");
        this.Text_CPF.setText("");
        this.Text_Cidade.setText("");
        this.Text_Complemento.setText("");
        this.Text_Data_Nascimento.setText("");
        this.Text_Email.setText("");
        this.Text_Login.setText("");
        this.Text_Logradouro.setText("");
        this.Text_Nome_Funcionario.setText("");
        this.Text_Numero.setText("");
        this.Text_Outro.setText("");
        this.Text_RG.setText("");
        this.Text_Senha.setText("");
    }
    private void Text_Data_NascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_Data_NascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_Data_NascimentoActionPerformed
    public Date getData(){
        return Pessoa_Generica.transformaData(this.Text_Data_Nascimento.getText().trim());
    }
    private void Text_Nome_FuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_Nome_FuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_Nome_FuncionarioActionPerformed
    public String getNome(){
        return this.Text_Nome_Funcionario.getText().trim();
    }
    private void Radio_MasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_MasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_MasculinoActionPerformed
    public String getSexo(){
        if (this.Radio_Masculino.isSelected())
            return "M";
        return "F";
    }
    private void Radio_FemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_FemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Radio_FemininoActionPerformed

    private void Text_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_EmailActionPerformed
    public String getEmail(){
        return this.Text_Email.getText().trim();
    }
    private void Text_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_LoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_LoginActionPerformed
    public String getLogin(){
        return this.Text_Login.getText().trim();
    }
    private void Text_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_SenhaActionPerformed
    public String getSenha(){
        return this.Text_Senha.getText().trim();
    }
    private void Text_CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_CPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_CPFActionPerformed
    public String getCPF(){
        return this.Text_CPF.getText().trim();
    }
    private void Text_RGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_RGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_RGActionPerformed
    public String getRG(){
        return this.Text_RG.getText().trim();
    }
    private void Text_OutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_OutroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_OutroActionPerformed
    public String getOutro(){
        return this.Text_Outro.getText().trim();
    }
    private void Text_NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_NumeroActionPerformed
    public String getNumero(){
        return this.Text_Numero.getText().trim();
    }
    private void Text_LogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_LogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_LogradouroActionPerformed
    public String getLogradouro(){
        int retorno= this.Box_Tipo_Logradouro.getSelectedIndex();
        if(retorno == 0) return "Rua";
        if(retorno == 1) return "Avenida";
        if(retorno == 2) return "Praça";
	return "";
    }
    public String getTipoLogradouro(){
        return this.Text_Logradouro.getText().trim();
    }
    private void Text_CEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_CEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_CEPActionPerformed
    public String getCEP(){
        return this.Text_CEP.getText().trim();
    }
    private void Text_ComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_ComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_ComplementoActionPerformed
    public String getComplemento(){
        return this.Text_Complemento.getText().trim();
    }
    private void Text_BairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_BairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_BairroActionPerformed
    public String getBairro(){
        return this.Text_Bairro.getText().trim();
    }
    private void Text_CidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_CidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_CidadeActionPerformed
    public String getCidade(){
        return this.Text_Cidade.getText().trim();
    }
    private void Button_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ConfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_ConfirmarActionPerformed
    public void Button_ConfirmarActionListener(ActionListener evt) {                                                 
        Button_Confirmar.addActionListener(evt);
    }
    private void Button_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SairActionPerformed
    public void Button_SairActionListener(ActionListener evt) {                                                 
        Button_Sair.addActionListener(evt);
    }
    private void Box_Estado_CivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_Estado_CivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_Estado_CivilActionPerformed

    private void Box_EspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_EspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_EspecialidadeActionPerformed

    private void Box_Tipo_LogradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Box_Tipo_LogradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Box_Tipo_LogradouroActionPerformed
    public String getEstadoCivil(){
        int retorno= this.Box_Estado_Civil.getSelectedIndex();
        if(retorno == 0) return "Solteiro";
        if(retorno == 1) return "Casado";
        if(retorno == 2) return "Separado";
	if(retorno == 3) return "Divorciado";
	if(retorno == 4) return "Viuvo";
        return "";
    }
    public String getCargo(){
        int retorno= this.Box_Cargo.getSelectedIndex();
        if(retorno == 0) return "Médico";
        if(retorno == 1) return "Enfermeiro";
        if(retorno == 2) return "Secretário";
        if(retorno == 3) return "Outro";
        return "";
    }
    public String getEspecialidade(){
        int retorno= this.Box_Especialidade.getSelectedIndex();
        if(retorno == 0) return "Outro";
		if(retorno == 1) return "Acupuntura";
		if(retorno == 2) return "Alergia e Imunologia";
		if(retorno == 3) return "Anestesiologia";
		if(retorno == 4) return "Angiologia";
		if(retorno == 5) return "Oncologia";
		if(retorno == 6) return "Cardiologia";
		if(retorno == 7) return "Cirurgia Cardiovascular";
		if(retorno == 8) return "Cirurgia da Mão";
		if(retorno == 9) return "Cirurgia de cabeça e pescoço";
		if(retorno == 10) return "Cirurgia do Aparelho Digestivo";
		if(retorno == 11) return "Cirurgia Geral";
		if(retorno == 12) return "Cirurgia Pediátrica";
		if(retorno == 13) return "Cirurgia Plástica";
		if(retorno == 14) return "CirurgiaTorácica";
		if(retorno == 15) return "Cirurgia Vascular";
		if(retorno == 16) return "Clínica Médica";
		if(retorno == 17) return "Coloproctologia";
		if(retorno == 18) return "Dermatologia";
		if(retorno == 19) return "Endocrinologia e Metabologia";
		if(retorno == 20) return "Endoscopia";
		if(retorno == 21) return "Gastroenterologia";
		if(retorno == 22) return "Genética médica";
		if(retorno == 23) return "Geriatria";
		if(retorno == 24) return "Ginecologia e obstetrícia";
		if(retorno == 25) return "Hematologia e Hemoterapia";
		if(retorno == 26) return "Homeopatia";
		if(retorno == 27) return "Infectologia";
		if(retorno == 28) return "Mastologia";
		if(retorno == 29) return "Medicina de Família e Comunidade";
		if(retorno == 30) return "Medicina do Trabalho";
		if(retorno == 31) return "Medicina do Tráfego";
		if(retorno == 32) return "Medicina Esportiva";
		if(retorno == 33) return "Medicina Física e Reabilitação";
		if(retorno == 34) return "Medicina Intensiva";
		if(retorno == 35) return "Medicina Legal e Perícia Médica";
		if(retorno == 36) return "Medicina Nuclear";
		if(retorno == 37) return "Medicina Preventiva e Social";
		if(retorno == 38) return "Nefrologia";
		if(retorno == 39) return "Neurocirurgia";
		if(retorno == 40) return "Neurologia";
		if(retorno == 41) return "Nutrologia";
		if(retorno == 42) return "Obstetrícia";
		if(retorno == 43) return "Oftalmologia";
		if(retorno == 44) return "Ortopedia e Traumatologia";
		if(retorno == 45) return "Otorrinolaringologia";
		if(retorno == 46) return "Patologia";
		if(retorno == 47) return "Pediatria";
		if(retorno == 48) return "Pneumologia";
		if(retorno == 49) return "Psiquiatria";
		if(retorno == 50) return "Radiologia";
		if(retorno == 51) return "Radioterapia";
		if(retorno == 52) return "Reumatologia";
		if(retorno == 53) return "Urologia";
        return "";
    }
    public String getEstado(){
        int retorno= this.Box_Cargo.getSelectedIndex();
        if(retorno == 0) return "Acre (AC)";
	if(retorno == 1) return "Alagoas (AL)";
	if(retorno == 2) return "Amapá (AP)";
	if(retorno == 3) return "Amazonas (AM)";
	if(retorno == 4) return "Bahia (BA)";
	if(retorno == 5) return "Ceará (CE)";
	if(retorno == 6) return "Distrito Federal (DF)";
	if(retorno == 7) return "Espírito Santo (ES)";
	if(retorno == 8) return "Goiás (GO)";
	if(retorno == 9) return "Maranhão (MA)";
	if(retorno == 10) return "Mato Grosso (MT)";
	if(retorno == 11) return "Mato Grosso do Sul (MS)";
	if(retorno == 12) return "Minas Gerais (MG)";
	if(retorno == 13) return "Pará (PA) ";
	if(retorno == 14) return "Paraíba (PB)";
	if(retorno == 15) return "Paraná (PR)";
	if(retorno == 16) return "Pernambuco(PE)";
	if(retorno == 17) return "Piauí (PI)";
	if(retorno == 18) return "Rio de Janeiro (RJ)";
	if(retorno == 19) return "Rio Grande do Norte (RN)";
	if(retorno == 20) return "Rio Grande do Sul (RS)";
	if(retorno == 21) return "Rondônia (RO)";
	if(retorno == 22) return "Roraima (RR)";
	if(retorno == 23) return "Santa Catarina (SC)";
	if(retorno == 24) return "São Paulo (SP)";
	if(retorno == 25) return "Sergipe (SE)";
	if(retorno == 26) return "Tocantins (TO)";
        return "";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Box_Cargo;
    private javax.swing.JComboBox Box_Especialidade;
    private javax.swing.JComboBox Box_Estado;
    private javax.swing.JComboBox Box_Estado_Civil;
    private javax.swing.JComboBox Box_Tipo_Logradouro;
    private javax.swing.JButton Button_Confirmar;
    private javax.swing.JButton Button_Sair;
    private javax.swing.JRadioButton Radio_Feminino;
    private javax.swing.JRadioButton Radio_Masculino;
    private javax.swing.JTextField Text_Bairro;
    private javax.swing.JFormattedTextField Text_CEP;
    private javax.swing.JFormattedTextField Text_CPF;
    private javax.swing.JTextField Text_Cidade;
    private javax.swing.JTextField Text_Complemento;
    private javax.swing.JFormattedTextField Text_Data_Nascimento;
    private javax.swing.JTextField Text_Email;
    private javax.swing.JTextField Text_Login;
    private javax.swing.JTextField Text_Logradouro;
    private javax.swing.JTextField Text_Nome_Funcionario;
    private javax.swing.JFormattedTextField Text_Numero;
    private javax.swing.JTextField Text_Outro;
    private javax.swing.JFormattedTextField Text_RG;
    private javax.swing.JPasswordField Text_Senha;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
