/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Pessoa.Pessoa_Generica;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.util.ArrayList;
import java.lang.String;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class Tela_Consultar_Atendimento_View extends javax.swing.JInternalFrame {
    public ArrayList Noticias = new ArrayList<String>();
    private ArrayList paciente;
    private ArrayList consulta;
    private ArrayList medico;
    public String[] pacienteSel;
    public String[] consultaSel;
    public String[] medicoSel;
    public void ZeraNoticias(){
        this.Noticias.clear();
        this.AtualizaDados();
    }
    public void setNoticias(String c){
        this.Noticias.add(c);
        this.AtualizaDados();
    }
    public String getNoticias(int i){
        return (String) this.Noticias.get(i);
    }
    public String getReceita(){
        return this.Text_Receita.getText();
    }
    public void setReceita(String t){
        this.Text_Receita.setText(t);
    }
    /**
     * Creates new form Tela_Cadastro_Funcionarios_View
     */
    public String[] setComboBoxConsulta(){
        //this.consultaSel=null;
        this.consultaSel = new String[consulta.size()];
        this.Combo_Box_Consulta.removeAllItems();
        this.Text_Receita.setText("");
        //this.Combo_Box_Consulta.addItem("");
        for(int i=0;i<consulta.size();i++){
            this.consultaSel[i]= new String((String)this.consulta.get(i));
            this.Combo_Box_Consulta.addItem(this.consultaSel[i]);
        }
        return consultaSel;
    }
    public String[] setComboBoxPaciente(){
        //this.pacienteSel=null;
        this.pacienteSel = new String[paciente.size()];
        this.Combo_Box_Paciente.removeAllItems();
        //this.Combo_Box_Paciente.addItem("");
        for(int i=0;i<paciente.size();i++){
            this.pacienteSel[i]= new String((String)this.paciente.get(i));
            this.Combo_Box_Paciente.addItem(this.pacienteSel[i]);
        }
        return pacienteSel;
    }
    public String[] setComboBoxMedico(){
        //this.medicoSel=null;
        this.medicoSel = new String[medico.size()];
        this.Combo_Box_Medica.removeAllItems();
        //this.Combo_Box_Medica.addItem("");
        for(int i=0;i<medico.size();i++){
            this.medicoSel[i]= new String((String)this.medico.get(i));
            this.Combo_Box_Medica.addItem(this.medicoSel[i]);
        }
        return this.medicoSel;
    }
    public String getPaciente(){
        return this.pacienteSel[this.Combo_Box_Paciente.getSelectedIndex()];
    }
    public String getConsulta(){
        return this.consultaSel[this.Combo_Box_Consulta.getSelectedIndex()];
    }
    public String getMedico(){
        return this.medicoSel[this.Combo_Box_Medica.getSelectedIndex()];
    }
    public void setPaciente(ArrayList paciente) {
        this.paciente=null;
        this.paciente = paciente;
        this.setComboBoxPaciente();
    }
    public void setConsulta(ArrayList consulta) {
        this.consulta=null;
        this.consulta = consulta;
        this.setComboBoxConsulta();
    }
    public void setMedico(ArrayList medico) {
        this.medico=null;
        this.medico = medico;
        this.setComboBoxMedico();
    }
    public Tela_Consultar_Atendimento_View() {        
        this.setIcon();
        this.paciente = new ArrayList<String>();
        initComponents();
        habilitaConsulta(false);
        this.Text_Receita.setLineWrap(true);
        this.Text_Receita.setWrapStyleWord(true);
        this.habilitaConsulta(false);
        this.habilitaMedico(false);
        
    }
    public void habilitaConsulta(boolean value){
        this.Combo_Box_Consulta.setEnabled(value);
    }
    public void habilitaMedico(boolean value){
        this.Combo_Box_Medica.setEnabled(value);
    }
    public void setIcon(){
        initComponents();
         setFrameIcon(new ImageIcon(this.getClass().getResource("../Imagens/princ.png")));
    }
    public void setText(String str){
        this.Text_Receita.setText(str);
    }
    public void AtualizaDados(){
        Lista_Consultas.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                return Noticias.size();
            }
            public Object getElementAt(int i){
                return Noticias.get(i);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Button_Sair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_Consultas = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        Combo_Box_Paciente = new javax.swing.JComboBox();
        Combo_Box_Consulta = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Combo_Box_Medica = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Text_Receita = new javax.swing.JTextArea();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(960, 610));
        setMinimumSize(new java.awt.Dimension(960, 610));
        setPreferredSize(new java.awt.Dimension(960, 610));
        setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel1.setText("Consultas:");

        Button_Sair.setText("Sair");
        Button_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SairActionPerformed(evt);
            }
        });

        Lista_Consultas.setBackground(new java.awt.Color(240, 240, 240));
        Lista_Consultas.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Lista_Consultas.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                return Noticias.size();
            }
            public Object getElementAt(int i){
                return Noticias.get(i);
            }
        });
        jScrollPane1.setViewportView(Lista_Consultas);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel2.setText("Paciente:");

        Combo_Box_Paciente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Combo_Box_Paciente.setModel(new javax.swing.DefaultComboBoxModel());
        Combo_Box_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Box_PacienteActionPerformed(evt);
            }
        });

        Combo_Box_Consulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Combo_Box_Consulta.setModel(new javax.swing.DefaultComboBoxModel());
        Combo_Box_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Box_ConsultaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel3.setText("Consulta:");

        Combo_Box_Medica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Combo_Box_Medica.setModel(new javax.swing.DefaultComboBoxModel());
        Combo_Box_Medica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Box_MedicaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel4.setText("Receita:");

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel5.setText("Médico:");

        Text_Receita.setColumns(20);
        Text_Receita.setRows(5);
        jScrollPane2.setViewportView(Text_Receita);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Combo_Box_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Combo_Box_Medica, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(Button_Sair))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Combo_Box_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Sair)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Combo_Box_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Combo_Box_Medica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Combo_Box_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 253, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void Button_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SairActionPerformed

    private void Combo_Box_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Box_PacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_Box_PacienteActionPerformed

    private void Combo_Box_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Box_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_Box_ConsultaActionPerformed

    private void Combo_Box_MedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Box_MedicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_Box_MedicaActionPerformed
    public void Combo_Box_MedicaActionPerformed(ActionListener evt) {                                                 
        this.Combo_Box_Medica.addActionListener(evt);
    }
    public void Combo_Box_ConsultaActionPerformed(ActionListener evt) {                                                 
        Combo_Box_Consulta.addActionListener(evt);
    }
    public void Combo_Box_PacienteActionPerformed(ActionListener evt) {                                                 
        Combo_Box_Paciente.addActionListener(evt);
    }
    public void Button_SairActionListener(ActionListener evt) {                                                 
        Button_Sair.addActionListener(evt);
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Sair;
    private javax.swing.JComboBox Combo_Box_Consulta;
    private javax.swing.JComboBox Combo_Box_Medica;
    private javax.swing.JComboBox Combo_Box_Paciente;
    private javax.swing.JList Lista_Consultas;
    private javax.swing.JTextArea Text_Receita;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
