/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Pessoa.Pessoa_Generica;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.util.ArrayList;
import java.lang.String;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rodrigo
 */
public class Tela_Pagar_Consulta_View extends javax.swing.JInternalFrame {
    public ArrayList Noticias = new ArrayList<String>();
    private ArrayList paciente;
    private ArrayList consulta;
    public String[] pacienteSel;
    public String[] consultaSel;
    public void ZeraNoticias(){
        this.Noticias.clear();
        this.AtualizaDados();
    }
    public void setNoticias(String c){
        this.Noticias.add(c);
        this.AtualizaDados();
    }
    public String getNoticias(int i){
        return (String) this.Noticias.get(i);
    }
    /**
     * Creates new form Tela_Cadastro_Funcionarios_View
     */
    public String[] setComboBoxConsulta(){
        this.consultaSel=null;
        this.consultaSel = new String[consulta.size()];
        this.Combo_Box_Consulta.removeAllItems();
        for(int i=0;i<consulta.size();i++){
            this.consultaSel[i]= new String((String)this.consulta.get(i));
            this.Combo_Box_Consulta.addItem(this.consultaSel[i]);
        }
        return consultaSel;
    }
    public String[] setComboBoxPaciente(){
        this.pacienteSel=null;
        this.pacienteSel = new String[paciente.size()];
        this.Combo_Box_Paciente.removeAllItems();
        for(int i=0;i<paciente.size();i++){
            this.pacienteSel[i]= new String((String)this.paciente.get(i));
            this.Combo_Box_Paciente.addItem(this.pacienteSel[i]);
        }
        return pacienteSel;
    }
    public String getPaciente(){
        return this.pacienteSel[this.Combo_Box_Paciente.getSelectedIndex()];
    }
    public String getConsulta(){
        return this.consultaSel[this.Combo_Box_Consulta.getSelectedIndex()];
    }
    public void setPaciente(ArrayList paciente) {
        this.paciente=null;
        this.paciente = paciente;
        this.setComboBoxPaciente();
    }
    public void setConsulta(ArrayList consulta) {
        this.consulta=null;
        this.consulta = consulta;
        this.setComboBoxConsulta();
    }
    public Tela_Pagar_Consulta_View() {        
        this.setIcon();
        this.paciente = new ArrayList<String>();
        initComponents();
        habilitaConsulta(false);
    }
    public void habilitaConsulta(boolean value){
        this.Combo_Box_Consulta.setEnabled(value);
    }
    public void setIcon(){
        initComponents();
         setFrameIcon(new ImageIcon(this.getClass().getResource("../Imagens/princ.png")));
    }
    public void AtualizaDados(){
        Lista_Consultas.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                return Noticias.size();
            }
            public Object getElementAt(int i){
                return Noticias.get(i);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Button_Sair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista_Consultas = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        Combo_Box_Paciente = new javax.swing.JComboBox();
        Combo_Box_Consulta = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Button_Pagamento = new javax.swing.JButton();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(960, 610));
        setMinimumSize(new java.awt.Dimension(960, 610));
        setPreferredSize(new java.awt.Dimension(960, 610));
        setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel1.setText("Consultas não pagas:");

        Button_Sair.setText("Sair");
        Button_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SairActionPerformed(evt);
            }
        });

        Lista_Consultas.setBackground(new java.awt.Color(240, 240, 240));
        Lista_Consultas.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Lista_Consultas.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                return Noticias.size();
            }
            public Object getElementAt(int i){
                return Noticias.get(i);
            }
        });
        jScrollPane1.setViewportView(Lista_Consultas);

        jLabel2.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel2.setText("Paciente:");

        Combo_Box_Paciente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Combo_Box_Paciente.setModel(new javax.swing.DefaultComboBoxModel());
        Combo_Box_Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Box_PacienteActionPerformed(evt);
            }
        });

        Combo_Box_Consulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Combo_Box_Consulta.setModel(new javax.swing.DefaultComboBoxModel());
        Combo_Box_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Combo_Box_ConsultaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel3.setText("Pagar Consulta:");

        Button_Pagamento.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        Button_Pagamento.setText("Realizar Pagamento");
        Button_Pagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_PagamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Combo_Box_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 489, Short.MAX_VALUE)
                        .addComponent(Button_Sair))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Combo_Box_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Button_Pagamento)
                .addGap(321, 321, 321))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_Sair)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Combo_Box_Paciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Combo_Box_Consulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(Button_Pagamento)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void Button_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_SairActionPerformed

    private void Combo_Box_PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Box_PacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_Box_PacienteActionPerformed

    private void Combo_Box_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Combo_Box_ConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Combo_Box_ConsultaActionPerformed

    private void Button_PagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_PagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button_PagamentoActionPerformed
    public void Button_PagamentoActionPerformed(ActionListener evt) {                                                 
        this.Button_Pagamento.addActionListener(evt);
    }
    public void Combo_Box_ConsultaActionPerformed(ActionListener evt) {                                                 
        Combo_Box_Consulta.addActionListener(evt);
    }
    public void Combo_Box_PacienteActionPerformed(ActionListener evt) {                                                 
        Combo_Box_Paciente.addActionListener(evt);
    }
    public void Button_SairActionListener(ActionListener evt) {                                                 
        Button_Sair.addActionListener(evt);
    }  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Pagamento;
    private javax.swing.JButton Button_Sair;
    private javax.swing.JComboBox Combo_Box_Consulta;
    private javax.swing.JComboBox Combo_Box_Paciente;
    private javax.swing.JList Lista_Consultas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
