/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Notebook
 */
public class Tela_Login_View extends javax.swing.JFrame {
    /**
     * Creates new form TelaLogin
     */
    public Tela_Login_View() {
        this.setIcon();
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Login = new javax.swing.JButton();
        Button_out = new javax.swing.JButton();
        Label_Login = new javax.swing.JLabel();
        Label_Senha = new javax.swing.JLabel();
        Text_Login = new javax.swing.JTextField();
        Text_Senha = new javax.swing.JPasswordField();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jonas Gabriela");
        setAutoRequestFocus(false);
        getContentPane().setLayout(null);

        Button_Login.setText("Login");
        Button_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Login);
        Button_Login.setBounds(50, 90, 80, 23);

        Button_out.setText("Sair");
        Button_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_outActionPerformed(evt);
            }
        });
        getContentPane().add(Button_out);
        Button_out.setBounds(140, 90, 70, 23);

        Label_Login.setBackground(new java.awt.Color(0, 0, 0));
        Label_Login.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Label_Login.setText("Login:");
        getContentPane().add(Label_Login);
        Label_Login.setBounds(20, 20, 90, 20);

        Label_Senha.setBackground(new java.awt.Color(0, 0, 0));
        Label_Senha.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Label_Senha.setText("Senha:");
        getContentPane().add(Label_Senha);
        Label_Senha.setBounds(20, 50, 70, 20);

        Text_Login.setFont(new java.awt.Font("Lucida Calligraphy", 0, 12)); // NOI18N
        Text_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(Text_Login);
        Text_Login.setBounds(70, 20, 170, 20);

        Text_Senha.setNextFocusableComponent(Button_Login);
        Text_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_SenhaActionPerformed(evt);
            }
        });
        getContentPane().add(Text_Senha);
        Text_Senha.setBounds(70, 50, 130, 20);

        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/login.png"))); // NOI18N
        getContentPane().add(jLabel);
        jLabel.setBounds(0, -20, 500, 260);

        setSize(new java.awt.Dimension(462, 284));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void Button_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LoginActionPerformed
    }//GEN-LAST:event_Button_LoginActionPerformed
    public void Button_LoginActionListener(ActionListener evt) {                                             
        Button_Login.addActionListener(evt);
    }
    
    
    private void Text_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_LoginActionPerformed
    }//GEN-LAST:event_Text_LoginActionPerformed

    private void Text_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_SenhaActionPerformed
        
    }//GEN-LAST:event_Text_SenhaActionPerformed
    public void Text_SenhaActionPerformed(ActionListener evt) {                                           
        this.Text_Senha.addActionListener(evt);
    }
    private void Button_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_outActionPerformed
        this.dispose();
    }//GEN-LAST:event_Button_outActionPerformed
    public void Button_outActionListener(ActionListener evt) {                                             
        Button_out.addActionListener(evt);
    }
    public String GetLogin(){
        return this.Text_Login.getText().trim();
    }
    public String GetSenha(){
        return this.Text_Senha.getText().trim();
    }
    
    public void SetVazio(){
        this.Text_Login.setText(null);
        this.Text_Senha.setText(null);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Login_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Login;
    private javax.swing.JButton Button_out;
    private javax.swing.JLabel Label_Login;
    private javax.swing.JLabel Label_Senha;
    private javax.swing.JTextField Text_Login;
    private javax.swing.JPasswordField Text_Senha;
    private javax.swing.JLabel jLabel;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../Imagens/icon.png")));
    }
}
